export const GlobalStyles = {
  colors: {
    primary: '#386A1F',
    onPrimary: '#FFFFFF',
    primaryContainer: '#B8F397',
    onPrimaryContainer: '#072100',
    secondary: '#55624C',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D9E7CB',
    onSecondaryContainer: '#131F0D',
    tertiary: '#386666',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#BBEBEC',
    onTertiaryContainer: '#002020',
    error: '#BA1A1A',
    errorContainer: '#FFDAD6',
    onError: '#FFFFFF',
    onErrorContainer: '#410002',
    background: '#FDFDF6',
    onBackground: '#1A1C18',
    surface: '#FDFDF6',
    onSurface: '#1A1C18',
    surfaceVariant: '#E0E4D7',
    onSurfaceVariant: '#43483E',
    outline: '#74796D',
    inverseOnSurface: '#F1F1EA',
    inverseSurface: '#2F312D',
    inversePrimary: '#9DD67E',
    shadow: '#000000',
    surfaceTint: '#386A1F',
    outlineVariant: '#C3C8BB',
    scrim: '#000000',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  typography: {
    body: {
      fontSize: 16,
      lineHeight: 24,
      fontFamily: 'System',
    },
    heading: {
      fontSize: 24,
      lineHeight: 32,
      fontFamily: 'System',
    },
  },
  borderRadius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
  }
};
